@DotNetTemplate_HostAddress = http://localhost:5230

GET {{DotNetTemplate_HostAddress}}/users/
Accept: application/json

###

POST {{DotNetTemplate_HostAddress}}/users/
Accept: application/json
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com"
}
###
