@DotNetTemplate_HostAddress = http://localhost:5230

GET {{DotNetTemplate_HostAddress}}/users/
Accept: application/json

###

POST {{DotNetTemplate_HostAddress}}/users/
Accept: application/json
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Doe",
  "email": "doe.joe@example.com",
  "password": "P@ssw0rd3",
  "phoneNumber": "0790000002"
}

###

POST {{DotNetTemplate_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "doe.mark@example.com",
  "password": "P@ssw0rd2"
}
